[package]
name = "skani"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
bio = "*"
rand = "0.8.3"
fxhash = "*"
clap = "3"
debruijn = "*"
partitions = "*"
num-traits = "*"
needletail = "*"
simple-logging= "*"
log = "*"
rayon = "*"
nohash-hasher = "*"
smallvec = { version = "*", features = ["union","serde","write"] }
serde = "*"
bincode = "*"
intervallum = "*"
rust-lapper = "*"
gcollections = "*"
statrs = "*"

[dev-dependencies]
assert_cmd = "1.0.1"
predicates = "1"


[profile.release]
opt-level = 3

[profile.dev]
#opt-level = 1
opt-level = 3

#[rust]
#debuginfo-level = 1
